language: python
cache: pip
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
env:
  global:
    - PGPORT=5433
    - STORM_POSTGRES_URI="postgres://travis:travis@localhost:5433/travis"
install:
  - pip install -e .[dev,doc]
before_script:
  - psql -c "ALTER USER travis WITH PASSWORD 'travis';"
script:
  - STORM_CEXTENSIONS=0 pytest
  - STORM_CEXTENSIONS=1 pytest
  - sphinx-build doc/ doc-build/
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  committer-from-gh: true
  local-dir: doc-build
  on:
    branch: master
