language: python
cache: pip
matrix:
  include:
    - python: 2.7
    - python: 3.3
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true
      env:
        - PGPORT=5432
        - STORM_POSTGRES_URI="postgres://travis:travis@localhost:5432/travis"
addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
env:
  global:
    - PGPORT=5433
    - STORM_POSTGRES_URI="postgres://travis:travis@localhost:5433/travis"
install:
  - pip install -e .[dev,doc]
before_script:
  - psql -c "ALTER USER travis WITH PASSWORD 'travis';"
script:
  - STORM_CEXTENSIONS=0 pytest
  - STORM_CEXTENSIONS=1 pytest
  - sphinx-build doc/ doc-build/
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  committer-from-gh: true
  local-dir: doc-build
  on:
    branch: master
