#!/bin/bash -eu

PGHBA=/etc/postgresql/*/main/pg_hba.conf
PGCONF=/etc/postgresql/*/main/postgresql.conf
PGINIT=/etc/init.d/postgresql*
MYSQL_PRIVS="GRANT ALL PRIVILEGES ON *.* TO '$USER'@'localhost' IDENTIFIED BY '' WITH GRANT OPTION;"

echo " * Fixing localhost access to postgres, restarting service"
sudo sed -i.bak -r 's/(host.*127\.0\.0\.1.*)\s+\w+$/\1 trust/' $PGHBA
sudo sed -i.bak -r 's/(host.*::1\/128.*)\s+\w+$/\1 trust/' $PGHBA
sudo sed -i.bak -r 's/(host.*::1\/128.*)\s+\w+$/\1 trust/' $PGHBA
sudo sed -i.bak -r 's/#(max_prepared_transactions.*)= 0/\1 = 200/' $PGCONF
sudo $PGINIT restart

echo " * Create postgres superuser ($USER - will fail if existing)"
# If this fails, we will get errors later, so don't fail.
sudo -u postgres createuser --superuser $USER || /bin/true

echo " * Granting all mysql privs to $USER"
mysql -u root -e "$MYSQL_PRIVS"

echo " * Create DB Test Fixtures (will fail if existing)"
createdb storm_test || /bin/true
mysql -u $USER -e "CREATE DATABASE storm_test CHARACTER SET utf8;" || /bin/true

echo " * Testing DB Access for user:$USER"
pg_dump storm_test > /dev/null
mysqldump -u $USER storm_test > /dev/null

echo " * All Done."


