#!/bin/bash -eu

CODENAME=$(lsb_release -cs)

function apt_get() {
    sudo DEBIAN_FRONTEND=noninteractive apt-get \
        -y -o Dpkg::Options::='--force-confold' $*
}

if [[ $CODENAME > "vivid" ]]; then
    PYTHON_MYSQL="python-mysqldb python-pymysql"
else
    PYTHON_MYSQL="python-mysqldb"
fi

apt_get install --no-install-recommends \
    $PYTHON_MYSQL \
    mysql-server \
    postgresql \
    pgbouncer \
    build-essential \
    python-django \
    python-fixtures \
    python-psycopg2 \
    python-testresources \
    python-transaction \
    python-twisted \
    python-zope.component \
    python-zope.security \
    python-setuptools


echo " * All Done!"
