#!/bin/bash -eu

function apt_get() {
    sudo DEBIAN_FRONTEND=noninteractive apt-get \
        -y -o Dpkg::Options::='--force-confold' $*
}

apt_get install --no-install-recommends \
    python-mysqldb \
    mysql-server \
    postgresql \
    pgbouncer \
    build-essential \
    python-fixtures \
    python-psycopg2 \
    python-testresources \
    python-transaction \
    python-twisted \
    python-zope.component \
    python-zope.security \
    python-setuptools


echo " * All Done!"
