name: Publish documentation

on:
  push:
    branches:
      - master

jobs:
  docs-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install -e .[doc]
      - name: Build documentation
        run: |
          sphinx-build doc/ doc-build/
          touch doc-build/.nojekyll
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2
        with:
          emptyCommits: false
          username: Andreas Runfalk
          useremail: andreas@runfalk.se
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./doc-build/
