name: Publish documentation

on:
  push:
    branches:
      - master

jobs:
  docs-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install -e .[doc]
      - name: Build documentation
        run: |
          sphinx-build doc/ doc-build/
          touch doc-build/.nojekyll
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v1
        with:
          allow_empty_commit: false
          build_dir: doc-build/
          committer_name: Andreas Runfalk
          committer_email: andreas@runfalk.se
          keep_history: true
        env:
          GITHUB_PAT: ${{ secrets.PERSONAL_TOKEN }}
